### ISSUE TITLE
Server errors out on stop

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#4] opened 2016-10-04 00:10 UTC
not sure if even an issue (or if it ever will be), but the game throws an error when the host stops the server

[2016-09-03/20:06:30] [Client/Receive(127.0.0.1:2143)] [DEBUG] Stopping Thread: "Client/Receive(127.0.0.1:2143)"java.net.SocketException: Socket closed
[2016-09-03/20:06:30] [Client/Receive] [DEBUG] Stopping Thread: "Client/Receive"
[2016-09-03/20:06:30] [Client/Send] [DEBUG] Stopping Thread: "Client/Send"
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(Unknown Source)

```
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at ca.afroman.network.TCPSocket.receive(TCPSocket.java:46)
at ca.afroman.game.TCPReceiver.onRun(TCPReceiver.java:52)
at ca.afroman.thread.DynamicThread.run(DynamicThread.java:106)
```

also the server host might not want to get "Server Closed" when closing the server, not sure on this one

//Note - the error tries to output while the the game is debugging, possibly causing a freeze (it did for me)

**Comment by ButterscotchV** [comment] 2016-10-04 00:19
It's probably fine; it's just closing the socket that isn't needed anymore unexpectedly (just killing the socket) Unless it's spammed like crazy

**Comment by defaultsamson** [comment] 2016-10-04 01:19
This is caused by the TCP socket when the socket is closed. It is because the input and output streams are blocked in I/O operations on separate threads, therefore they throw errors when they're forcefully shutdown. This isn't an issue, as it is the desired behaviour of these TCP sockets, and there's no real "safe" way to close them otherwise.

**Closed as completed** 2016-10-04 01:20 UTC
